import math
import networkx as nx
import numpy as np
from sklearn.cluster import KMeans

from classes.street_light import StreetLight

def add_nodes_to_multipath_domain_common_neighbors(mpl_domain, nodes, verbose):
    street_lights = [node for node in nodes if isinstance(node, StreetLight)]

    # Function to calculate the PDR between two nodes
    def calculate_pdr(node1, node2):
        return node1.link_quality[node2]

    for i in range(len(street_lights)):
        if i + 2 > len(street_lights):
            continue
        for j in range(i + 1, i + 2):
        # for j in range(i + 1, len(street_lights)):
            sl1 = street_lights[i]
            sl2 = street_lights[j]

            common_neighbors = set(sl1.neighbors).intersection(sl2.neighbors)
            if common_neighbors:
                best_neighbor = None
                max_pdr_product = 0

                # ELEGIR NEIGHBOR QUE MAXIMICE PDR
                for neighbor in common_neighbors:
                    pdr_sl1_to_neighbor = calculate_pdr(sl1, neighbor)
                    pdr_neighbor_to_sl2 = calculate_pdr(neighbor, sl2)
                    pdr_product = pdr_sl1_to_neighbor * pdr_neighbor_to_sl2

                    if pdr_product > max_pdr_product:
                        max_pdr_product = pdr_product
                        best_neighbor = neighbor

                if best_neighbor:
                    mpl_domain.add_node(best_neighbor, verbose)
                    mpl_domain.add_node(sl1, verbose)
                    mpl_domain.add_node(sl2, verbose)
                    if verbose:
                        print(f"Added {best_neighbor.get_id()} as common neighbor of {sl1.get_id()} and {sl2.get_id()}")

    if verbose:
        print(f"MPL Domain: {mpl_domain}")



def add_nodes_to_multipath_domain_common_neighbors_range_extended(mpl_domain, nodes, verbose):
    street_lights = [node for node in nodes if isinstance(node, StreetLight)]

    # Function to calculate the PDR between two nodes
    def calculate_pdr(node1, node2):
        return node1.link_quality[node2]

    # Step through street lights in increments of 2
    for i in range(0, len(street_lights) - 2, 2):
        sl1 = street_lights[i]
        sl2 = street_lights[i + 1]
        sl3 = street_lights[i + 2]

        # Find common neighbors among the three street lights
        common_neighbors = set(sl1.neighbors).intersection(sl2.neighbors).intersection(sl3.neighbors)

        if common_neighbors:
            best_neighbor = None
            max_pdr_product = 0

            # Choose the neighbor that maximizes the combined PDR product
            for neighbor in common_neighbors:
                pdr_sl1_to_neighbor = calculate_pdr(sl1, neighbor)
                pdr_neighbor_to_sl2 = calculate_pdr(neighbor, sl2)
                pdr_neighbor_to_sl3 = calculate_pdr(neighbor, sl3)
                
                # Calculate the product of PDRs
                pdr_product = pdr_sl1_to_neighbor * pdr_neighbor_to_sl2 * pdr_neighbor_to_sl3

                if pdr_product > max_pdr_product:
                    max_pdr_product = pdr_product
                    best_neighbor = neighbor

            if best_neighbor:
                # Add the best common neighbor and the three street lights to the MPL domain
                mpl_domain.add_node(best_neighbor, verbose)
                mpl_domain.add_node(sl1, verbose)
                mpl_domain.add_node(sl2, verbose)
                mpl_domain.add_node(sl3, verbose)
                
                if verbose:
                    print(f"Added {best_neighbor.get_id()} as common neighbor of {sl1.get_id()}, {sl2.get_id()}, and {sl3.get_id()}")

    if verbose:
        print(f"MPL Domain: {mpl_domain}")


def optimize_domain_with_common_neighbor_and_mst(mpl_domain, nodes, common_neighbor_domain, verbose):
    """
    Optimize the MPL domain by combining the common neighbor approach with a refined MST-based approach 
    to ensure essential node selection while minimizing transmissions.

    Args:
    - mpl_domain: The MPL domain object.
    - nodes: List of all nodes (Street Lights and others).
    - common_neighbor_domain: The domain generated by the common neighbor approach.
    - verbose: Print additional debug information if True.
    """
    # Step 1: Get nodes from the common neighbor domain
    common_neighbor_domain_nodes = common_neighbor_domain.get_nodes()

    # Step 2: Build a graph from the common neighbor domain with all current nodes and edges
    graph = nx.Graph()
    
    # Add all nodes in the Common Neighbor Domain to the graph
    for node in common_neighbor_domain_nodes:
        graph.add_node(node.id)
    
    # Add edges to the graph, excluding direct edges between Street Lights
    for node in common_neighbor_domain_nodes:
        for neighbor in node.neighbors:
            if neighbor in common_neighbor_domain_nodes:
                link_quality = node.link_quality[neighbor]
                weight = 1 / link_quality  # Inverse of link quality as weight
                graph.add_edge(node.id, neighbor.id, weight=weight)
    
    # Step 3: Compute the Minimum Spanning Tree (MST) for the reduced graph
    mst = nx.minimum_spanning_tree(graph, weight='weight')
    
    # Step 4: Refine the MST to only include essential nodes and connections
    essential_nodes = set()
    for u, v in mst.edges:
        essential_nodes.add(u)
        essential_nodes.add(v)

    # Maintain a copy of the original nodes before clearing
    original_nodes = list(mpl_domain.nodes)

    # Clear the existing MPL domain nodes
    mpl_domain.remove_nodes()
    
    # Step 5: Re-add only the essential nodes and their critical connections
    street_lights = [node for node in nodes if isinstance(node, StreetLight)]
    for street_light in street_lights:
        mpl_domain.add_node(street_light, verbose)
    
    for node_id in essential_nodes:
        node = next(node for node in nodes if node.id == node_id)
        if node not in mpl_domain.get_nodes():
            mpl_domain.add_node(node, verbose)

    # Add edges from MST that connect only the essential nodes
    for u, v in mst.edges:
        node_u = next(node for node in nodes if node.id == u)
        node_v = next(node for node in nodes if node.id == v)
        
        # Ensure both nodes of the edge are added to the domain:
        mpl_domain.add_node(node_u, verbose)
        mpl_domain.add_node(node_v, verbose)
        
        if verbose:
            print(f"Edge ({u}, {v}) with weight {mst.edges[u, v]['weight']} added to the final domain.")

    # Step 6: Iteratively remove non-essential nodes to minimize transmissions
    for node in original_nodes:
        if node not in street_lights and node not in essential_nodes:
            # Check if removing this node would disconnect any street light
            connected_street_lights = {sl for sl in street_lights if nx.has_path(graph, node.id, sl.id)}
            if len(connected_street_lights) < len(street_lights):
                # If all street lights remain connected, remove the node
                if verbose:
                    print(f"Removing node {node.get_id()} to reduce transmissions.")
                mpl_domain.remove_node(node)

    if verbose:
        print(f"Optimized Domain: Nodes added to ensure all street lights are interconnected with essential nodes only.")
        domain_nodes = [node.get_id() for node in mpl_domain.nodes]
        print(f"Nodes in Optimized MPL Domain: {domain_nodes}")



def calculate_num_clusters(width, height, num_nodes, num_street_lights, tx_range):
    """
    Calculate the optimal number of clusters based on the area of the map, the number of nodes, 
    the number of street lights, and the transmission range.

    Args:
        width (int): Width of the map area.
        height (int): Height of the map area.
        num_nodes (int): Total number of nodes in the network.
        num_street_lights (int): Number of street lights in the network.
        tx_range (int): Transmission range of each node.

    Returns:
        int: Calculated number of clusters.
    """
    # Calculate the area of the map
    area = width * height
    
    # Calculate the effective transmission area of a single node
    tx_area = tx_range ** 2

    # Calculate the number of clusters using the given formula
    num_clusters = math.ceil((area / tx_area) * (num_street_lights / num_nodes))
    
    return num_clusters


def add_nodes_to_cluster_based_domain(mpl_domain, nodes, num_clusters, verbose):
    """
    Add nodes to the MPL domain based on clustering to improve reliability while minimizing the number of transmissions.

    Args:
    - mpl_domain: The MPL domain object.
    - nodes: List of all nodes.
    - num_clusters: Number of clusters.
    - verbose: Print additional debug information if True.
    """
    # Step 1: Separate street lights and other nodes
    street_lights = [node for node in nodes if isinstance(node, StreetLight)]
    other_nodes = [node for node in nodes if not isinstance(node, StreetLight)]

    # Step 2: Ensure all street lights are added to the MPL domain
    for street_light in street_lights:
        mpl_domain.add_node(street_light, verbose)

    # Step 3: Prepare positions for KMeans clustering (only for nodes that are not street lights)
    # This step prepares the data required for the K-means clustering algorithm.
    # This is done because the K-means clustering algorithm needs a set of points in a multi-dimensional space 
    # to operate on. In this case, the space is two-dimensional (x, y coordinates).
    positions = np.array([[node.x, node.y] for node in other_nodes]) 

    # Step 4: Perform K-means clustering for other nodes.
    # The objetive is to perform clustering on the non-street-light nodes to group them into num_clusters clusters.
    # random_state=0: Sets the seed for the random number generator, ensuring that the results are reproducible.
    # .fit(positions) runs the K-means algorithm on the positions data.
    kmeans = KMeans(n_clusters=num_clusters, random_state=0).fit(positions)
    # After fitting, kmeans.labels_ gives an array of cluster labels, indicating which cluster each node belongs to.
    labels = kmeans.labels_

    # The purpose is to partition the nodes into groups (clusters) such that nodes within each cluster are as close to 
    # each other as possible, and nodes in different clusters are as far from each other as possible.
    # This helps in identifying key nodes (close to the centroid) that can provide better coverage and reliability when 
    # added to the MPL domain.

    # Step 5: For each cluster, find the node closest to the centroid and add to the MPL domain
    # The idea is to select the most representative node from each cluster and add it to the MPL domain.
    
    # Dictionary to store nodes assigned to each cluster. The keys are cluster indices (0 to num_clusters - 1).
    cluster_assignments = {i: [] for i in range(num_clusters)}
    
    # Loop through each cluster.
    for cluster_index in range(num_clusters):    # It processes each cluster one by one.
        # List of nodes that belong to the current cluster.
        # It uses the labels array from the previous step to filter nodes corresponding to the current cluster.
        cluster_nodes = [other_nodes[i] for i in range(len(other_nodes)) if labels[i] == cluster_index] 
        # The centroid is the average position of all nodes in the cluster and represents the "center" of the cluster.
        centroid = kmeans.cluster_centers_[cluster_index]

        # Find the node closest to the centroid.

        # This line finds the node in cluster_nodes that is closest to the centroid.
        # np.linalg.norm(np.array([node.x, node.y]) - centroid) calculates the Euclidean distance between each node's position and the centroid.
        # min(...) finds the node with the smallest distance to the centroid.
        closest_node = min(cluster_nodes, key=lambda node: np.linalg.norm(np.array([node.x, node.y]) - centroid))
        # Adds this closest node to the MPL domain, assuming it provides good connectivity and reliability within the cluster.
        mpl_domain.add_node(closest_node, verbose)
        cluster_assignments[cluster_index].append(closest_node)

    if verbose:
        print(f"Cluster-Based Domain: Created {num_clusters} clusters and added nodes accordingly.")
        for cluster_idx, nodes in cluster_assignments.items():
            node_ids = [node.get_id() for node in nodes]
            print(f"Cluster {cluster_idx}: {node_ids}")